/* Generated by Yosys 0.65+71 (git sha1 e56c6a954-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "..\\rtl\\cpu_top.v:1.1-90.10" *)
module cpu_top(clk, instr);
  (* src = "..\\rtl\\cpu_top.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "..\\rtl\\cpu_top.v:3.18-3.23" *)
  input [31:0] instr;
  wire [31:0] instr;
endmodule
